kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
networking:
  podSubnet: "10.100.0.0/16"
  serviceSubnet: "10.110.0.0/16"
nodes:
- role: control-plane
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
