kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cluster2
networking:
  ipFamily: dual
  podSubnet: "10.200.0.0/16,a:200::/108"
  serviceSubnet: "10.210.0.0/16,a:210::/108"
  disableDefaultCNI: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    controllerManager:
      extraArgs:
        node-cidr-mask-size-ipv6: "112"
- role: worker
- role: worker
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
