---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
  annotations:
    io.cilium/global-service: "true"
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: echoserver-daemonset
  labels:
    app: echoserver
spec:
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: echoserver
        image: ealen/echo-server:latest
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
